# Generated by Django 5.2.1 on 2025-05-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_category_menuresto_ordermenu_ordermenudetail_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuresto',
            old_name='descritption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ordermenu',
            old_name='cahsier',
            new_name='cashier',
        ),
        migrations.RenameField(
            model_name='ordermenu',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
